### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by AstralGitHub** [provsalt/LightningDeath#19]
[18:42:02.012] [Server thread/CRITICAL]: TypeError: "pocketmine\network\mcpe\protocol\AddActorPacket::create(): Argument #12 ($syncedProperties) must be of type pocketmine\network\mcpe\protocol\types\entity\PropertySyncData, array given, called in phar:///home/container/plugins/LightningDeath.phar/src/LightningListener.php on line 38" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/AddActorPacket" at line 56
--- Stack trace ---
  #0 plugins/LightningDeath.phar/src/LightningListener(38): pocketmine\network\mcpe\protocol\AddActorPacket::create(int 3, int 1, string[24] minecraft:lightning_bolt, object pocketmine\math\Vector3#177567, null, float 174.9462890625, float 0, float 0, float 0, array[0], array[0], array[0])
  #1 plugins/LightningDeath.phar/src/LightningListener(32): provsalt\lightningdeath\LightningListener->Lightning(object pocketmine\player\Player#129607)
  #2 pmsrc/src/event/RegisteredListener(60): provsalt\lightningdeath\LightningListener->onDeath(object pocketmine\event\player\PlayerDeathEvent#126038)
  #3 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerDeathEvent#126038)
  #4 pmsrc/src/player/Player(2251): pocketmine\event\Event->call()
  #5 pmsrc/src/entity/Entity(549): pocketmine\player\Player->onDeath()
  #6 pmsrc/src/entity/Entity(587): pocketmine\entity\Entity->kill()
  #7 pmsrc/src/entity/Living(189): pocketmine\entity\Entity->setHealth(float -4.5)
  #8 pmsrc/src/entity/Entity(534): pocketmine\entity\Living->setHealth(float -4.5)
  #9 pmsrc/src/entity/Living(524): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#177577)
  #10 pmsrc/src/player/Player(2373): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#177577)
  #11 pmsrc/src/player/Player(1772): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#177577)
  #12 pmsrc/src/network/mcpe/handler/InGamePacketHandler(512): pocketmine\player\Player->attackEntity(object pocketmine\player\Player#129607)
  #13 pmsrc/src/network/mcpe/handler/InGamePacketHandler(324): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#173816)
  #14 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/InGamePacketHandlerX(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#173667)
  #15 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): CLADevs\VanillaX\network\handler\InGamePacketHandlerX->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#173667)
  #16 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object CLADevs\VanillaX\network\handler\InGamePacketHandlerX#178211)
  #17 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#173667, string[49] .........................P...^..B+.l?............)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(183): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[76] c.abb.b.j...S.H..w.....(.....\..VbU..X.Z..`(............\.p..l..........3 ..)
  #19 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 1, string[85] .#...`.-y...K8...}...'.........u.1j*..Pb.TFA...z^....O.....rJ.!....u...S.2Vz....)
  #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(113): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#129960)
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #22 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #23 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1671561722.0519)
  #24 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #25 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #26 pmsrc/src/PocketMine(362): pocketmine\server()
  #27 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by AstralGitHub** [comment]
(when i kill someone)

**Comment by provsalt** [comment]
No longer crashes in 55abc98f30523f4fbf694cebb82ed931eec9eb92. Enjoy your Christmas present.
