### ISSUE TITLE
No Lightning Sound

### ISSUE THREAD

**Issue by mrpwes** [provsalt/LightningDeath#5]

**Comment by provsalt** [comment]
this is a known issue.Its just not implemented yet

**Comment by mrpwes** [comment]
still waiting for update keep it up thanks dude.

**Comment by provsalt** [comment]
It has been added thanks for the wait

**Comment by mrpwes** [comment]
still don't have sound ... i can't locate the error i think at my server ??
PMMP 3.11.6 v1.14.0
LightningDeath v1.1.2 from https://poggit.pmmp.io/p/LightningDeath/1.1.2

**Comment by provsalt** [comment]
Thats strange.Do you have any logs/error?

**Comment by mrpwes** [comment]
i dont have any, Is there a plugin that block LightningDeath ... ? Don't mind me if u r busy ill find way to track that issue :)
![image](https://user-images.githubusercontent.com/31194909/77515967-7a1b4e80-6eb4-11ea-8f00-7f0bb072b423.png)

**Comment by provsalt** [comment]
Fixed in 405e62943b176a632d78281445ebc0db65154a4d
